#' @title Time Completeness of Carbonate Deposition
#'
#' @description Calculate fraction of time during which carbonate sediment accumulates.
#'
#' @details Used to calculate proportion of time in carbonate rocks represented by sediment. Inverse is the proportion of time reflected by hiatuses.
#'
#' @param x an object of class "column" generated by carbColumn().
#'
#' @export
#' 
#' @return Fraction of time in a stratigraphic column represented by at least some rock.
#'
#' geom <- geometry(fallLineY=150, shoreX=200, deltaWidth=100, deltaToeY=-100, marginWidth=500, resolution='medium', nonMarAlpha=0.5, marineAlpha=2.0, duration=12.0, timeStep=0.001)
#' subs <- subsidence(geometry=geom, startingLeft=0.0, startingRight=20.0, netChangeFactor=1.0)
#' eust <- eustasy(geometry=geom, period=3.0, amplitude=30, symmetry=0.5, phase='rising', shape=4, netRise=0.0)
#' depths <- c(0.0,  2.0,  5.0, 10.0, 40.0, 100.0)
#' rates  <- c(0.0, 40.0, 15.0, 10.0, 5.0, 2.0)
#' sedi <- carbSediment(depths, rates, lagTime=0.02, initialWaterDepth=2)
#' colu <- carbColumn(geometry=geom, subsidence=subs, eustasy=eust, carbSediment=sedi, locationKm=50.0)
#' carbCompleteness(colu) 
#' 1 - carbCompleteness(colu)  # fractional incompleteness
#'

carbCompleteness <- function(x) {
	waterDepth <- -x$elevation
	totalTime <- length(waterDepth)
	depositionalTime <- length(waterDepth[waterDepth >= 0])
	fractionalCompleteness <- depositionalTime / totalTime
	return(fractionalCompleteness)
}