#' @title Stratigraphic Columns Simulating Shallow-marine Carbonate Deposition
#'
#' @description Create a stratigraphic column of shallow-marine carbonates..
#'
#' @details Create a stratigraphic column of shallow-marine carbonates, based on a model similar to that of Read et al. (1986; Geology 14:107–110). Model includes tectonic subsidence, eustasy, and depth-dependent carbonate sedimentation rates, but not isostasy, compaction, or erosion.
#'
#' @param geometry an object of class [`geometry`].
#' @param subsidence an object of class [`subsidence`].
#' @param eustasy an object of class [`eustasy`].
#' @param carbSediment an object of class [`carbSediment`].
#' @param locationKm a number indicating where in the basin the column will be located,  
#'   specified as the distance (in km) from the left edge of the basin.
#'
#' @export
#' 
#' @return `column` returns an object of class "column".
#' 
#' A column object consists of a data frame with five columns; each row corresponds to one sedimentary deposit. `modelTime` is the model time step in millions of years, `thickness` is the thickness of the deposit in meters, `stratPosition` is the height (in meters) within the stratigraphic column of the base of the deposit, `facies` is the facies of the deposit (carbonate, in this case), and `elevation` is the elevation (in meters above sea level) at which the deposit accumulated.
#'
#' @examples
#' geom <- geometry(fallLineY=150, shoreX=200, deltaWidth=100, deltaToeY=-100,  
#'   marginWidth=500, resolution='medium', nonMarAlpha=0.5, marineAlpha=2.0,  
#'   duration=12.0, timeStep=0.001)
#' subs <- subsidence(geometry=geom, startingLeft=0.0, startingRight=20.0,  
#'   netChangeFactor=1.0)
#' eust <- eustasy(geometry=geom, period=3.0, amplitude=30, symmetry=0.5, phase='rising',  
#'   shape=4, netRise=0.0)
#' depths <- c(0.0,  2.0,  5.0, 10.0, 40.0, 100.0)
#' rates  <- c(0.0, 40.0, 15.0, 10.0, 5.0, 2.0)
#' sedi <- carbSediment(depths, rates, lagTime=0.02, initialWaterDepth=2)
#' colu <- carbColumn(geometry=geom, subsidence=subs, eustasy=eust, carbSediment=sedi,  
#'   locationKm=50.0)
#' 
#' @rdname column
#' @export column

carbColumn <- function(geometry, subsidence, eustasy, carbSediment, locationKm=NULL) {
	if (!("carbSediment" %in% class(carbSediment))) {
		stop("ERROR: carbSediment must be an object generated by carbSediment()", call.=FALSE)
	}
	
# 	cat(paste("lag time:", carbSediment$lagTime, "\n"))
# 	cat(paste("initial water depth:", carbSediment$initialWaterDepth))
# 	cat(paste("length of production curve:", nrow(carbSediment$productionCurve), "\n"))
# 	cat(paste("first pair: ", carbSediment$productionCurve$waterDepth[1], carbSediment$productionCurve$rate[1], "\n"))
# 	last <- nrow(carbSediment$productionCurve)
# 	cat(paste("last pair: ", carbSediment$productionCurve$waterDepth[last], carbSediment$productionCurve$rate[last], "\n"))
	
	if (is.null(locationKm)) {
		locationKm <- 1
	}
	timeStep <- geometry$timeStep
	duration <- geometry$duration
	modelTime <- eustasy$timeSeries$timePoint
	totalSediment <- rep(0, length(modelTime))
	waterDepth    <- rep(0, length(modelTime))
	waterDepth[1] <- carbSediment$initialWaterDepth
	lagCounter    <- 0
	eustaticSealevel <- eustasy$timeSeries$seaLevel
	# position 
	subsidence <- -subsidence$rates[, locationKm / geometry$deltaX] * modelTime
	accommodation <- carbSediment$initialWaterDepth + eustaticSealevel + subsidence

	# Sedimentation; must be done sequentially to check for lag time
	for (i in 2:length(modelTime)) {
		startingWaterDepth <- accommodation[i] - totalSediment[i-1]
		# check for lag
		if (startingWaterDepth <=0) {  # subaerial
			# print("subaerial")
			lagCounter <- carbSediment$lagTime
			newSediment <- carbThickness(startingWaterDepth, timeStep, carbSediment)
		} else if (lagCounter > 0) {   # submarine, but within the lag time
			# print("lag time")
			lagCounter <- lagCounter - timeStep
			newSediment <- 0
		} else {                       # submarine, outside of the lag time
			# print("normal marine")
			newSediment <- carbThickness(startingWaterDepth, timeStep, carbSediment)
		}
		totalSediment[i] <- totalSediment[i-1] + newSediment
		waterDepth[i] <- accommodation[i] - totalSediment[i]
	}
	# plot(waterDepth, totalSediment, type="l")

	thickness <- c(0, diff(totalSediment))
	stratPosition <- totalSediment
	facies <- rep("carbonate", length(modelTime))
	elevation <- -waterDepth
	column <- data.frame(modelTime=modelTime, thickness=thickness, stratPosition=stratPosition, facies=facies, elevation=elevation)

	class(column) <- "column"
	return(column)
}
