#' @title Stratigraphic Columns from Sedflux
#'
#' @description Convert a stratigraphic column generated by the Sedflux model into one compatible with strataR.
#'
#' @details Create a stratigraphic column compatible with strataR from a column generated by Sedflux by providing a data frame containing columns named time, stratPosition, and waterDepth.
#'
#' @param sedfluxColumn a dataframe generated by importing a column produced by the Sedflux model. Column names must include time, stratPosition, and waterDepth.
#' @param timeConversion factor to convert the duration of a sedflux run.
#'
#' @export
#' 
#' @return `column` returns an object of class "column".
#' 
#' A column object consists of a data frame with five columns; each row corresponds to one sedimentary deposit. `modelTime` is the model time step in millions of years, `thickness` is the thickness of the deposit in meters, `stratPosition` is the height (in meters) within the stratigraphic column of the base of the deposit, `facies` is the facies of the deposit (floodplain, channel, or marine), and `elevation` is the elevation (in meters above sea level) at which the deposit accumulated.
#'
#' @examples
#' \dontrun{
#' data(sedflux)
#' colu <- columnFromSedflux(sedflux, timeConversion=3)
#' }
#'

columnFromSedflux <- function(sedfluxColumn, timeConversion=1) {
	yearsToMy <- 0.000001
	modelTime <- sedfluxColumn$time * yearsToMy * timeConversion
	stratPosition <- sedfluxColumn$stratPosition
	elevation <- -sedfluxColumn$waterDepth   # TODO [] correct for a marine column?
	thickness <- diff(stratPosition)
	thickness <- c(0, thickness)
	facies <- rep("carbonate", length(modelTime))
	strataRColumn <- data.frame(modelTime, thickness, stratPosition, facies, elevation)
	return(strataRColumn)
}
