#' Example Stratigraphic Column through an Incised Valley
#'
#' Data generated by `column` in strataR: `column(sedBasin, locationKm=190.0,  
#'   setting='valley', pChannel=0.05, channelDepth=2.0)`
#'
#' @docType data
#'
#' @usage data(coluValley)
#'
#' @format An object of class [`column`].
#'
#' @keywords datasets
#'
#' @examples
#' data(coluValley)
#' plot(coluValley)
"coluValley"