#' Example Eustatic Sea-Level History
#'
#' Data generated by `eustasy` in strataR: `eustasy(geometry=geom, netRise=30.0)`
#'
#' @docType data
#'
#' @usage data(eust)
#'
#' @format An object of class [`eustasy`].
#'
#' @keywords datasets
#'
#' @examples
#' data(eust)
#' plot(eust)
"eust"