#' Example Geometry for Basin Simulation
#'
#' Data generated by `geometry` in strataR: `geometry(fallLineY=150, shoreX=200,  
#'   deltaWidth=100, deltaToeY=-100, marginWidth=600, nonMarAlpha=0.5, marineAlpha=2.0,  
#'   duration=3.0, timeStep=0.01)`
#'
#' @docType data
#'
#' @usage data(geom)
#'
#' @format An object of class [`geometry`].
#'
#' @keywords datasets
#'
#' @examples
#' data(geom)
#' summary(geom)
"geom"