#' Example Stratigraphic Column that Includes Marine Strata
#'
#' Data generated by `geometry` in strataR: `column(sedBasin, locationKm=250.0,  
#'   setting='interfluve', pChannel=0.05, channelDepth=2.0)`
#'
#' @docType data
#'
#' @usage data(marcolu)
#'
#' @format An object of class [`column`].
#'
#' @keywords datasets
#'
#' @examples
#' data(marcolu)
#' plot(marcolu)
"marcolu"