#' Example Fossil Occurrences in Marine Strata
#'
#' Data generated by `marineOccurrences` in strataR: `marineOccurrences(marcolu, marspec,  
#'   sampleSpacing=0.5)`
#'
#' @docType data
#'
#' @usage data(maroccu)
#'
#' @format An object of class [`marineOccurrences`].
#'
#' @keywords datasets
#'
#' @examples
#' data(maroccu)
#' data(marcolu)
#' data(marspec)
#' plot(maroccu, column=marcolu, marineSpecies=marspec)
"maroccu"
