#' Example Marine Species
#'
#' Data generated by `marineSpecies` in strataR: `marineSpecies(timeStep=0.001,  
#'   extRate=0.25, startingSpecies=200, durationMy=5.0, minPD=0, maxPD=100, meanDT=10,  
#'   sdDT=2, meanLogPA=log(25), sdLogPA=log(5), maxPA=100)`
#'
#' @docType data
#'
#' @usage data(marspec)
#'
#' @format An object of class [`marineSpecies`].
#'
#' @keywords datasets
#'
#' @examples
#' data(marspec)
#' plot(marspec)
"marspec"