#' Example Fossil Occurrences in Nonmarine Strata
#'
#' Data generated by `occurrences` in strataR: `occurrences(column=coluValley,  
#'   species=spec)`
#'
#' @docType data
#'
#' @usage data(occu)
#'
#' @format An object of class [`occurrences`].
#'
#' @keywords datasets
#'
#' @examples
#' data(occu)
#' data(coluValley)
#' data(spec)
#' plot(occu, column=coluValley, species=spec)
"occu"
