#' Example Sedimentary Basin
#'
#' Data generated by `basin` in strataR: `basin(geometry=geom, subsidence=subs,  
#'   eustasy=eust, sediment=sedi)`
#'
#' @docType data
#'
#' @usage data(sedBasin)
#'
#' @format An object of class [`basin`].
#'
#' @keywords datasets
#'
#' @examples
#' data(sedBasin)
#' plot(sedBasin)
"sedBasin"