#' Example Sediment Flux to a Basin
#'
#' Data generated by `sediment` in strataR: `sediment(geometry=geom, startingVolume=60)`
#'
#' @docType data
#'
#' @usage data(sedi)
#'
#' @format An object of class [`sediment`].
#'
#' @keywords datasets
#'
#' @examples
#' data(sedi)
#' plot(sedi)
"sedi"