#' Example Nonmarine Species
#'
#' Data generated by `species` in strataR: `species(timeStep=0.001, extRate=0.25,  
#'   startingSpecies=1000, durationMy=5.0, minPE=0, maxPE=200, meanET=10, sdET=2,  
#'   meanLogPA=log(25), sdLogPA=log(5), maxPA=100)`
#'
#' @docType data
#'
#' @usage data(spec)
#'
#' @format An object of class [`species`].
#'
#' @keywords datasets
#'
#' @examples
#' data(spec)
#' plot(spec)
"spec"