#' Example Subsidence History
#'
#' Data generated by `subsidence` in strataR: `subsidence(geometry=geom, startingLeft=0.0,  
#'   startingRight=1.0)`
#'
#' @docType data
#'
#' @usage data(subs)
#'
#' @format An object of class [`subsidence`].
#'
#' @keywords datasets
#'
#' @examples
#' data(subs)
#' data(geom)
#' plot(subs, geometry=geom, type='lines')
"subs"